name: Build Windows App

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Enable Windows Desktop Build
      run: flutter config --enable-windows-desktop

    - name: Download App Dependencies
      run: flutter pub get

    - name: Compile Production Windows EXE
      run: flutter build windows --release

    - name: Upload Finished App Folder
      uses: actions/upload-artifact@v4
      with:
        name: IPTV-Player-Windows
        path: build/windows/x64/runner/Release/
